
page: 1982_FIFA_World_Cup_squads

# mappings filenames for teams (note: MUST match order in source page)
teams:
- cmr # Cameroon  -- Group 1
- ita # Italy
- per # Peru
- pol # Poland
- alg # Algeria   -- Group 2
- aut # Austria
- chi # Chile
- frg # West Germany
- arg # Argentina  -- Group 3
- bel # Belgium
- slv # El Salvador
- hun # Hungary
- tch # Czechoslovakia   -- Group 4
- eng # England
- fra # France
- kuw # Kuwait
- hon # Honduras          -- Group 5
- nir # Northern Ireland
- esp # Spain
- yug # Yugoslavia
- bra # Brazil           -- Group 6
- nzl # New Zealand
- sco # Scotland
- urs # Soviet Union

