
page: 1994_FIFA_World_Cup_squads

# mappings filenames for teams (note: MUST match order in source page)
teams:
- col # Colombia    -- Group A
- rou # Romania
- sui # Switzerland
- usa # United States
- bra # Brazil      -- Group B
- cmr # Cameroon
- rus # Russia
- swe # Sweden
- bol # Bolivia      -- Group C
- ger # Germany
- kor # South Korea
- esp # Spain
- arg # Argentina    -- Group D
- bul # Bulgaria
- gre # Greece
- nga # Nigeria
- ita # Italy        -- Group E
- mex # Mexico
- nor # Norway
- irl # Ireland
- bel # Belgium      -- Group F
- mar # Morocco
- ned # Netherlands
- ksa # Saudi Arabia

